- name: Wait for cloud-init to finish updating apt sources list
  wait_for:
    path: /etc/apt/sources.list
    search_regex: cloud-init

- name: Upgrade packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Install JRE
  apt:
    package: openjdk-{{ spring_boot_app_java_version }}-jre-headless
    state: present

- name: Install RNG
  apt:
    package: rng-tools
    state: present

- name: Install systemd script for the app
  template:
    src: app.service.j2
    dest: /lib/systemd/system/app.service
  notify: Refresh systemd

- name: Make the app start on boot
  service:
    name: app
    enabled: yes

- name: Upload JAR file
  copy:
    src: "{{ spring_boot_app_jar_path }}"
    dest: /home/ubuntu/app.jar

- name: Write properties files
  blockinfile:
    name: /home/ubuntu/application.yml
    block: "{{ spring_boot_app_properties }}"
    create: yes
  when: spring_boot_app_properties is defined
